name: Application Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies for AuthorizationServer
        run: dotnet restore SHP.AuthorizationServer.Web/SHP.AuthorizationServer.Web.csproj
      - name: Build IdentityServer
        run: dotnet build --no-restore SHP.AuthorizationServer.Web/SHP.AuthorizationServer.Web.csproj
      - name: Run Integration Tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" SHP.AuthorizationServer.IntegrationTests/SHP.AuthorizationServer.IntegrationTests.csproj
      - name: Integration Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: CoreAPI and IdentityServer Integration Tests # Name of the check run which will be created
          path: SHP.AuthorizationServer.IntegrationTests/TestResults/test-results.trx # Path to test results
          reporter: dotnet-trx # Format of test results

      - name: Run Unit Tests
        run: dotnet test --logger "trx;LogFileName=test-results.trx" SHP.AuthorizationServer.Tests/SHP.AuthorizationServer.Tests.csproj
      - name: Unit Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: CoreAPI and IdentityServer Unit Tests # Name of the check run which will be created
          path: SHP.AuthorizationServer.Tests/TestResults/test-results.trx # Path to test results
          reporter: dotnet-trx # Format of test results
